#!/usr/bin/env sh

{{- if eq .chezmoi.hostname "mbp" }}
export HOME="/Users/{{ .chezmoi.username }}"
{{- else if or (eq .chezmoi.hostname "lemur") (eq .chezmoi.hostname "omen") }}
export HOME="{{ .chezmoi.homeDir }}"
{{- end }}

export PATH="$HOME/.bin:$PATH"
export EDITOR="emacs -nw"
export BROWSER="google-chrome-stable"

export STARSHIP_CONFIG="$HOME/.config/starship/config.toml"

export BRAIN_PROJ_DIR="$HOME/projects/brain-web"
export BRAIN_DIR="$HOME/brain/contents"
export ZK_NOTEBOOK_DIR="$HOME/brain/contents"

{{- if eq .chezmoi.hostname "mbp" }}
export CC="/usr/local/bin/gcc-11"
{{- end }}

brainloc () {
  cd $BRAIN_DIR
}

# ADDITIONAL PATHS
export OPT_DIR="$HOME/opt"

# Fly
if [ -d "$HOME/.fly" ]
then
    export FLYCTL_INSTALL="$HOME/.fly"
    export PATH="$FLYCTL_INSTALL/bin:$PATH"
fi

{{- if or (eq .chezmoi.hostname "lemur") (eq .chezmoi.hostname "omen") }}
# MPICH
MPICH_FOLDER="/opt/mpich/"
if [ -d $MPICH_FOLDER ]
then
    export PATH="$MPICH_FOLDER/bin:$PATH"
    export MANPATH="$MPICH_FOLDER/share/man:$MANPATH"
    export PKG_CONFIG_PATH="$MPICH_FOLDER/lib/pkgconfig:$PKG_CONFIG_PATH"
    export LD_LIBRARY_PATH=$MPICH_FOLDER/lib:$LD_LIBRARY_PATH
    export C_INCLUDE_PATH="$MPICH_FOLDER/include:$C_INCLUDE_PATH"
fi

# Perl5
PERL5_FOLDER="$HOME/perl5"
if [ -d "$PERL5_FOLDER" ]
then
   export PATH="$PERL5_FOLDER/bin:$PATH"
   export PERL5LIB="$PERL5_FOLDER/lib/perl5:$PERL5LIB"
   export PERL_LOCAL_LIB_ROOT="$PERL5_FOLDER:$PERL_LOCAL_LIB_ROOT"
   export PERL_MB_OPT="--install_base\ \"$PERL5_FOLDER\""
   export PERL_MB_OPT="INSTALL_BASE=\"$PERL5_FOLDER\""
fi
{{- end }}

# Rust

export CARGO_FOLDER="$HOME/.cargo"
if [ -f "$CARGO_FOLDER/env" ]
then
  source "$CARGO_FOLDER/env"
fi

export ASDF_FOLDER="$OPT_DIR/asdf"
if [ -f "$ASDF_FOLDER/asdf.sh" ]
then
    source "$ASDF_FOLDER/asdf.sh"
fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
export CONDA_FOLDER="$OPT_DIR/anaconda3"
__conda_setup="$('$CONDA_FOLDER/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$CONDA_FOLDER/etc/profile.d/conda.sh" ]; then
        . "$CONDA_FOLDER/etc/profile.d/conda.sh"
    else
        export PATH="$CONDA_FOLDER/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<