name: hpc 
channels:
  - conda-forge
dependencies:
  - python==3.10.1 
  - pip
  - jupyterlab
  - matplotlib
  - pandas
  - numpy
  - seaborn
  - cffi
  - networkx
  - holoviews
  - hvplot
  - pygraphviz
  - pydot
  - pip:
    - darshan==3.3.1.0

