add_newline = true

[character]
success_symbol = "[➜](bold green)"

[package]
disabled = true

[custom.giturl]
# disabled = true
description = "Display symbol for remote Git server"
command = "check-git-remote"
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
shell = ["bash", "--noprofile", "--norc"]
format = "at $output  "

[gcloud]
format = 'on [$symbol]($style) '
